// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: account.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (
    owner, balnce, currency
) VALUES (
             $1, $2, $3
         )
RETURNING id, owner, balnce, currency, created_at
`

type CreateAccountParams struct {
	Owner    string `json:"owner"`
	Balnce   int64  `json:"balnce"`
	Currency string `json:"currency"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Owner, arg.Balnce, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balnce,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
